name: Daily Update
on:
  schedule:
    - cron: '30 18 * * *' # Runs at 12:00 AM IST (18:30 UTC)
  workflow_dispatch:      # Allows manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run Bot
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
          SHEET_KEY: ${{ secrets.SHEET_KEY }}
        run: python main.py
