name: Daily Update
on:
  schedule:
    - cron: '30 18 * * *' # Runs at 12:00 AM IST (18:30 UTC)
  workflow_dispatch:      # Allows manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Changed v3 to v4 here
      - uses: actions/checkout@v4
      # Changed v4 to v5 here
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt 
      
      - name: Run Fixer
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_KEY: ${{ secrets.SHEET_KEY }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        run: python fix_ids.py

      - name: Run Bot
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
          SHEET_KEY: ${{ secrets.SHEET_KEY }}
        run: python main.py

        # STEP 3: Re-Apply Formatting
      - name: Fix Formatting
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_KEY: ${{ secrets.SHEET_KEY }}
        run: python format_sheet.py
